### ISSUE TITLE
Should I PR my export plugin?

### ISSUE THREAD

**Issue by lzilioli** [TypingMind/awesome-typingmind#2]
I'm the creator of the export chats plugin, https://gist.github.com/lzilioli/a8298c8622a69768cec9f872c6bb128c

I'm wondering: would it make sense for me to open a PR with the plugin code directly into this repository? Do you have any plans to host this for users of typingmind to easily include?

It would also be very cool to be able to write unit tests for these plugins so that we can easily detect if a schema change breaks something. 

Also thanks for sharing my plugin here!

**Comment by trungdq88** [comment]
I think you should host it on your own GitHub repo (instead of a gist) and link the repo here. We'll look into a more official way to feature high-quality extensions and plugins soon.

Nice work on the extension btw! ❤️
